### ISSUE TITLE
Extracting data.rom from two PS Vita VNs by Favorite

### ISSUE THREAD

**Issue by 3cho0** [DCNick3/shin#35]
I found your tool when I was looking for a way to extract the data.rom found in the following two PS Vita ports:
(PCSG00462) Irotoridori no Sekai: World's End Re-Birth
(PCSG00901) AstralAir no Shiroki Eien: White Eternity

I tried to extract IroSeka's data.rom, but sdu gave me a bad magic number error. To fix that I changed "ROM" to "ROM2" in a hex editor, but now I get:
Error: Parsing ROM

Caused by:
    Unknown version: 0x00020001

Astral Air already has ROM2 in its file header, but I get the same issue there:
Error: Parsing ROM

Caused by:
    Unknown version: 0x00000001

There are many file formats inside that your tool also supports, such as .snr, .txa, .pic and .bup.

Is it possible to implement support for these two data.roms?
Also, is there a way to repack the data.rom file?

**Comment by DCNick3** [comment]
These appear to be some older versions of the ROM format (esp since they are on PS Vita). Supporting various versions of the format is not a priority for this project right now, as I am currently trying to make the game engine working, sorry! 

The Vita games are on my radar (I am at least trying to collect all the ROMs of them, so thanks for the names of those), but I just haven't gotten around to actually look at their older formats.

You might have better luck with 07th-mod tools from [enter_extractor](https://github.com/07th-mod/enter_extractor/) repo `blabla.py`, which is developed to extract .rom files seems to have support for files with `ROM ` magic. I also remember there being tools supporting other formats (.pic, ¿.bup?, ...), with some attempts to make it work across versions. It might be worth a try. 

You can also be interested in [ShinDataUtil](https://github.com/DCNick3/ShinDataUtil) (developed by me), as it also implements the repacking of `data.rom` (and also supports encoding of all the `.txa`, `.pic` and `.bup` files). But it was also developed for switch-era games (tested with Higurashi and KonoSuba), so it would probably of no direct interest.

**Comment by DCNick3** [comment]
Oh, https://github.com/ItaloKnox/ps3umi might also be useful, it seems to be developed for even older formats

**Comment by 3cho0** [comment]
Thank you for the quick answer!
I will definitely look into those tools, since repacking is inevitable.

In the meantime, I was also looking for other tools and managed to extract the data.rom by modifying the blabla.py from here:
https://github.com/07th-mod/enter_extractor

I replaced the 'utf-8' in line 36 with 'sjis' and it worked like a charm.

**Comment by 3cho0** [comment]
A couple of things to note here for Astral Air. I tried enter-extractor, ps3umi, ShinDataUtil and even GARbro, but unfortunately none of the tools support the files from the PS Vita.
The .pic files are PIC4, version 1 and .bup files are BUP4, version 2. I tried changing the version numbers and other stuff, but obviously that didn't work.

At least, I was able to convert the files from Irotoridori no Sekai to .png using enter-extractor, since that game was released a bit earlier than Astral Air. I guess, the most interesting part would be to repack the rom file with a translated script and replacing the voice files with higher quality versions from the PC release. Luckily, we have tools to convert from .wav to Vita's .at9 format.

I'll be keeping an eye on your tool, since it seems very promising. Maybe it can be used in the future to mod these games on console.

**Comment by DCNick3** [comment]
If you want translation, I would guess that you would be interested in PIC (used for CGs), TXA (used for UI elements & stuff, usually text is pre-rendered there) and SNR (the game scenario, obviously).

From my experience, supporting the PIC and TXA I think would be less effort, while SNR is kind of complicated.

What I am trying to do here with SNR is supporting the full instruction set, while only a few instructions are actually relevant for translation. I think I'll make a spin-off tool focused only on translation for that :thinking: 

I'll try to look into it on weekend if something unexpected won't come up.

Btw, I'm `dcnick3` on Discord and Telegram, add me if you want. Probably would be easier to communicate there

**Comment by 3cho0** [comment]
Thank you very much for the quick update! The extraction works nicely and translating the script should be doable, too.
Creating a patch.rom with modified assets might be easier indeed. I'll keep tinkering with currently available tools to check if it's possible to make this work on the Vita.

About the repacking process, I'm sure you've found Neurochitin's tools already, but I'll leave a link for other people to find:
https://gitlab.com/Neurochitin/kaleido/

He also made an english patch for Kaleido for the Switch and PS Vita using the patch.rom method:
https://gitlab.com/Neurochitin/miko_kaleido_patch

Other than (PCSG01294) Gensou Rougoku no Kaleidoscope, there is also (PCSG00517) Higurashi no Naku Koro ni Sui with a data.rom file inside. Just leaving this here, since you are researching games with these files.

**Comment by DCNick3** [comment]
I am currently compiling all the games (switch/vita) I know of into a spreadsheet and will work on a polyglot tool for all the ROM versions they use, so repacking should be figured out soon

**Comment by DCNick3** [comment]
[shin-translation-tools](https://github.com/DCNick3/shin-translation-tools) has support for extracting and packing ROM files now

**Comment by nini22P** [comment]
This is the pic to png scripts for AstralAir no Shiroki Eien White Eternity.

Additionally, I tried writing some png to pic scripts, but they never displayed properly.

<details>
<summary>Python code</summary>
<pre>
<code class="language-python">
import struct
import os
import io
import argparse
from PIL import Image

def lz77_decompress(data):
    if not data: return b""
    stream = io.BytesIO(data)
    out = bytearray()
    length = len(data)
    
    while stream.tell() < length:
        flag = stream.read(1)
        if not flag: break
        byte = flag[0]
        
        for i in range(8):
            if stream.tell() >= length: break
            if ((byte >> i) & 1) == 0:
                out.extend(stream.read(1))
            else:
                b = stream.read(2)
                if len(b) < 2: break
                val = int.from_bytes(b, 'big')
                count = (val >> 12) + 3
                offset = (val & 0xFFF) + 1
                
                start = len(out) - offset
                if start < 0:
                    out.extend(b'\x00' * count)
                else:
                    for _ in range(count):
                        out.append(out[start] if start < len(out) else 0)
                        start += 1
    return bytes(out)

def decode_dict_block(data, w, h, flags):

    stride = (w + 3) & ~3
    
    is_dict = (flags & 2) != 0
    use_inline_alpha = (flags & 1) != 0

    if not is_dict:
        return None

    if len(data) < 1024:
        return None

    palette = []
    for i in range(0, 1024, 4):
        b, g, r, a = data[i:i+4]
        palette.append((r, g, b, a))

    idx_start = 1024
    idx_len = stride * h
    
    if idx_start + idx_len > len(data):
        return None
        
    encoded_data = data[idx_start : idx_start + idx_len]

    alpha_data = None
    if not use_inline_alpha:
        a_start = idx_start + idx_len
        if a_start < len(data):
            alpha_data = data[a_start:]
    
    pixels = bytearray(w * h * 4)
    ptr = 0
    
    for row in range(h):
        row_offset = row * stride
        
        row_indices = encoded_data[row_offset : row_offset + w]
        
        row_alphas = None
        if alpha_data:
            if row_offset + w <= len(alpha_data):
                row_alphas = alpha_data[row_offset : row_offset + w]
        
        for col in range(w):
            if col < len(row_indices):
                idx = row_indices[col]
            else:
                idx = 0
                
            r, g, b, a = palette[idx]
            
            if row_alphas:
                a = row_alphas[col]
            
            pixels[ptr] = r
            pixels[ptr+1] = g
            pixels[ptr+2] = b
            pixels[ptr+3] = a
            ptr += 4
            
    return pixels

def convert_file(file_path, output_path):
    file_size = os.path.getsize(file_path)
    
    with open(file_path, 'rb') as f:
        if f.read(4) != b"PIC4":
            return False

        header = struct.unpack("<IIhhHHIII", f.read(28))
        version, file_size, origin_x, origin_y, effective_width, effective_height, flags, block_count, picture_id  = header

        blocks = []
        for i in range(block_count):
            blocks.append(struct.unpack("<HHI", f.read(8)))

        img = Image.new("RGBA", (effective_width, effective_height))
        processed_blocks = 0

        for i, (bx, by, offset) in enumerate(blocks):
            next_offset = blocks[i+1][2] if i < block_count - 1 else file_size
            max_len = next_offset - offset

            if offset >= file_size: continue
            f.seek(offset)
            
            tile_data = f.read(20)
            if len(tile_data) < 20: continue
            
            tile = struct.unpack("<HHHHHHHHI", tile_data)
            flags, opaque, trans, pad, w, h, comp_size = tile[0], tile[1], tile[2], tile[3], tile[6], tile[7], tile[8]
            
            skip = (opaque + trans) * 8 + (pad * 2)
            f.seek(skip, 1)

            data_len = comp_size if comp_size > 0 else (max_len - 20 - skip)
            if data_len <= 0: continue
            
            raw_data = f.read(data_len)
            if not raw_data: continue

            dec_data = lz77_decompress(raw_data)
            if not dec_data: continue

            pixel_bytes = decode_dict_block(dec_data, w, h, flags)
            
            if pixel_bytes:
                tile_img = Image.frombytes("RGBA", (w, h), bytes(pixel_bytes))
                img.paste(tile_img, (bx, by))
                processed_blocks += 1

        img.save(output_path)
        print(f"[Completed] {os.path.basename(file_path)} ({processed_blocks}/{block_count})")
        return True

def process_batch(input_path):
    abs_input = os.path.abspath(input_path)
    
    if os.path.isfile(abs_input):
        folder = os.path.dirname(abs_input)
        name = os.path.splitext(os.path.basename(abs_input))[0]
        out_path = os.path.join(folder, name + ".png")
        convert_file(abs_input, out_path)
    
    elif os.path.isdir(abs_input):
        parent_dir = os.path.dirname(abs_input)
        folder_name = os.path.basename(abs_input)
        output_dir = os.path.join(parent_dir, folder_name + "_png")
        
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            
        print(f"Output directory: {output_dir}")
        
        count = 0
        for root, dirs, files in os.walk(abs_input):
            for file in files:
                if file.lower().endswith(".pic"):
                    src = os.path.join(root, file)
                    name = os.path.splitext(file)[0]
                    dst = os.path.join(output_dir, name + ".png")
                    
                    if convert_file(src, dst):
                        count += 1
        
        print(f"Prcessed {count} files.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("input", help="Please input file or directory path.")
    args = parser.parse_args()
    
    if os.path.exists(args.input):
        process_batch(args.input)
    else:
        print("No such file or directory")

</code>
</pre>
</details>
